apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "datacube-wps.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Release.Name }}-wps
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "80"
    port: {{ .Values.wps.externalPort }}
    targetPort: {{ .Values.wps.internalPort }}
  selector:
    app: {{ template "datacube-wps.name" . }}
    release: {{ .Release.Name }}
