{{- $externalDb := .Values.global.externalDatabase }}
{{- $dc := .Values.global.datacube }}
{{- $index := .Values.index }}
{{- $image := .Values.global.image }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ $externalDb.database }}-index"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: index
spec:
  schedule: {{ $index.cron | quote }}
  successfulJobsHistoryLimit: {{ $index.historyLimit}}
  failedJobsHistoryLimit: {{ $index.historyLimit }}
  suspend: {{ $index.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ $externalDb.database }}-index"
          labels:
            heritage: {{.Release.Service | quote }}
            release: {{.Release.Name | quote }}
            chart: "{{.Chart.Name}}-{{.Chart.Version}}"
          annotations:
          {{- range $key, $value := $index.annotations }}
            {{ $key }}: {{ $value | quote }}
          {{- end }}
        spec:
          initContainers:
          - name: postgres-listener
            image: alpine
            command: ["sh", "-c", "for i in $(seq 1 200); do nc -z -w3 {{ $externalDb.host }} {{ $externalDb.port }} && exit 0 || sleep 3; done; exit 1"]
          containers:
          - name: datacube-index
            image: "{{ $image.repository }}:{{ $image.tag }}"
            imagePullPolicy: {{ $image.pullPolicy }}
            args: [ {{- range $index.dockerArgs }} {{ . | quote }}, {{ end -}} ]
            env:
            - name: WMS_CONFIG_URL
              {{- if $index.wmsConfigURL }}
              value: {{ $index.wmsConfigURL | quote }}
              {{- else }}
              value: {{ $dc.wmsConfigURL | quote }}
              {{- end }}
            - name: PRODUCT_URLS
              {{- if $index.products }}
              value: {{ template "helm-toolkit.utils.joinListWithSpace" $index.products }}
              {{- else }}
              value: {{ template "helm-toolkit.utils.joinListWithSpace" $dc.products }}
              {{- end }}
            - name: DC_S3_INDEX_BUCKET
              value: {{ $index.bucket | quote }}
            - name: DC_S3_INDEX_PREFIX
              value: {{ template "helm-toolkit.utils.joinListWithSpace" $index.prefix }}
            - name: DC_S3_INDEX_SUFFIX
              value: {{ $index.suffix | quote }}
            - name: DB_HOSTNAME
              value: {{ $externalDb.host | quote }}
            - name: DB_PORT
              value: {{ $externalDb.port | quote }}
            - name: DB_DATABASE
              value: {{ $externalDb.database | quote }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $externalDb.database }}
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $externalDb.database }}
                  key: postgres-password
            {{- if $index.additionalEnvironmentVars }}
            {{- range $arg, $value := $index.additionalEnvironmentVars }}
            - name: {{ $arg | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          restartPolicy: Never
          {{- with $index.resources }}
          resources:
            {{- with .limits }}
            limits:
              {{ if .cpu }}cpu: {{ .cpu | quote }} {{ end }}
              {{ if .memory }}memory: {{ .memory | quote }} {{ end }}
            {{- end }}
            {{- with .requests }}
              requests:
              {{ if .cpu }}cpu: {{ .cpu | quote }} {{ end }}
              {{ if .memory }}memory: {{ .memory | quote }} {{ end }}
            {{- end }}
          {{- end }}