dependencies:
  - name: datacube-index
    version: 0.2.12
    repository: "https://opendatacube.github.io/datacube-charts/charts/"
    condition: index.enabled
  - name: datacube-wps
    version: 0.1.2
    repository: "https://opendatacube.github.io/datacube-charts/charts/"
    condition: wps.enabled
  - name: datacube-dashboard
    version: 0.2.9
    repository: "https://opendatacube.github.io/datacube-charts/charts/"
    condition: cubedash.enabled
  - name: datacube-data
    version: 0.1.5
    repository: "https://opendatacube.github.io/datacube-charts/charts/"
    condition: data_orchestration.enabled
