# Default values for datacube-wms.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minReplicas: 1
maxReplicas: 2

global:
  datacube:
    configPath: /opt/odc/datacube.conf
    products: raw.githubusercontent.com/GeoscienceAustralia/dea-config/master/prod/products/nrt/sentinel/products.yaml
  clusterSecret: datakube.gadevs.ga
  clusterInfo:
    envName:
  externalDatabase:
    database: datacube
  image:
    repository: opendatacube/wms
    tag: latest
    pullPolicy: Always


postgresql:
  enabled: false
  postgresqlUsername: datacube
  postgresqlDatabase: datacube
  existingSecret: datacube
  service:
    port: 5432
  master:
    nodeSelector: {}
    affinity: {}
    tolerations: []
    podAnnotations: {}
    podLabels: {}
  resources: {}

##
## Datacube WMS configuration
##
wms:
  enabled: true
  maxSurge: 25%
  maxUnavailable: 25%
  externalPort: 80
  internalPort: 8000
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
  targetCpu: 10
  dockerArgs: [ "gunicorn", "-b", "0.0.0.0:8000", "-w", "4", "--keep-alive", "50", "--timeout", "120", "datacube_wms.wsgi" ]
  autoscaling: True
  annotations:
    iam.amazonaws.com/role: kubernetes-wms
wmsConfig:
  image: { }


##
## Prometheus Monitoring
##
prometheus:
  enabled: false
  path: "/opt/prometheus/"

##
## cProfiling, only enable for debugging and profiling purposes
##
profiling:
  enabled: true
  path: "/opt/profiling/"

wps:
  enabled: false

cubedash:
  enabled: false

data_orchestration:
  enabled: true

service:
  type: NodePort

ingress:
  ## Enable Ingress.
  ##
  enabled: false
  host:
