apiVersion: v1
kind: Secret
{{ $externalDb := .Values.global.externalDatabase }}
metadata:
  name: {{ $externalDb.database }}
  labels:
    app: {{ template "datacube.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- if $externalDb.password }}
  postgres-username: {{ $externalDb.username | b64enc | quote }}
  {{ else }}
  postgres-username: {{ .Release.Name | b64enc | quote }}
  {{ end -}}
  {{- if $externalDb.password }}
  postgres-password:  {{ $externalDb.password | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}